feat: add navigation
itsabdessalam/taskee pull request #3
Opened 2020-11-22 18:20 UTC by Floran-mtte

2020-11-22 19:44 UTC, codebynao approved these changes

2020-11-23 10:28 UTC, itsabdessalam commented on src/layouts/Footer.jsx
> +    let collapseText = document.getElementsByClassName("collapse__text");
Here, you browse the DOM several times, you can either store `document` in a variable and reuse it, or use `useRef` hook which gives you direct access to your current parent element and its children

2020-11-23 10:30 UTC, itsabdessalam commented on src/layouts/Footer.jsx
> +      for (let i = 0; i < sideBarText.length; i++) {
You add complexity by manipulating the styles inside a loop, why not just add a parent css class?

2020-11-23 10:30 UTC, itsabdessalam commented on src/layouts/Footer.jsx
> +    for (let i = 0; i < sideBarText.length; i++) {
Same as https://github.com/itsabdessalam/taskee/pull/3/files#r528603644

2020-11-23 10:33 UTC, itsabdessalam commented on src/components/TabItem.jsx
> +    height: 5%;
I'm not a big fan of using percentages like this, especially in our case

2020-11-23 10:44 UTC, itsabdessalam requested changes
I'v added some comments

Also, for your information 

![image](https://user-images.githubusercontent.com/23357835/99952999-da82c880-2d80-11eb-8b3e-cd42293d95f2.png)

![image](https://user-images.githubusercontent.com/23357835/99953030-e66e8a80-2d80-11eb-9a01-b17cfaf38b91.png)

When we switch to a mobile device after collapsing the sidebar, tab bar doesn't look good

![image](https://user-images.githubusercontent.com/23357835/99953123-1158de80-2d81-11eb-86e5-86bc867a7387.png)

2020-11-26 13:30 UTC, itsabdessalam approved these changes
LGTM!

2020-11-26 13:33 UTC, merged